// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJbaDZ2B3djEU3ezX8uLb1JcuhYR1MK-I',
    appId: '1:264958782482:web:a4dd83496e5ad3ba41bccb',
    messagingSenderId: '264958782482',
    projectId: 'what-if-c1f30',
    authDomain: 'what-if-c1f30.firebaseapp.com',
    storageBucket: 'what-if-c1f30.appspot.com',
    measurementId: 'G-ZS5W3QNNWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAwpQ2438zHavCWZLkGDsiSRHiEPwjW1M',
    appId: '1:264958782482:android:189ed6246bbfd67241bccb',
    messagingSenderId: '264958782482',
    projectId: 'what-if-c1f30',
    storageBucket: 'what-if-c1f30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtln2R-5GrSl14w_5-CtH59YYSHCOrpag',
    appId: '1:264958782482:ios:16a0bb0080eb5c1d41bccb',
    messagingSenderId: '264958782482',
    projectId: 'what-if-c1f30',
    storageBucket: 'what-if-c1f30.appspot.com',
    iosBundleId: 'com.example.whatifProject',
  );

}